engines:
  coffeelint:
    enabled: true
  scss-lint:
    enabled: true
  fixme:
    enabled: true

ratings:
  paths:
  - "src/*.coffee"
  - "src/*.sass"

exclude_paths:
  - *.js
  - features/**/*.cofffee
  - docs/*.js
  - demo/*.coffee
  - karma.conf.coffee
