version: 2

plugins:
  coffeelint:
    enabled: true
    config: coffeelint.json
  scss-lint:
    enabled: true

exclude_patterns:
  - "*.js"
  - "features/**/*.cofffee"
  - "docs/*.js"
  - "demo/*.coffee"
  - "karma.conf.coffee"
